name: Effort Project
on:
    push:
        branches: [ main ]
    pull_request:
       branches: [ main ]

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses : actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'
        
        - name: Restore dependecies 
          run: dotnet restore EffortProject.sln

        - name: Build
          run: dotnet build EffortProject.sln --configuration Release --no-restore

        - name: Run Tests
          run: dotnet test EffortProject.sln  --no-build --verbosity normal


        - name: Publish EffortProject
          run: dotnet publish   EffortProject/EffortProject.csproj -c Release -o ./publish
